name: Continuous Deployment

on:
    pull_request:
      branches:
        - main

    push:
      branches:
        - main

jobs:
    deploy:
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2

          - name: Set up SSH
            uses: webfactory/ssh-agent@v0.5.3
          - name: Run deploy sh script
            run:
              ssh -o StrictHostKeyChecking=no root@10.1.0.3